name: run api tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest-json-ctrf

    - name: Lint with flake8
      run: |
        flake8 tests --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests
      run: |
        pytest --ctrf $REPORT -n $PROC --testomatio report
      env:
        REPORT: 'test-results/report.json'
        PROC: 'auto'
        TESTOMATIO: ${{ secrets.TESTOMATIO_API_KEY }}
        TESTOMATIO_CODE_STYLE: 'pep8'

    - name: Generate Pretty Report
      if: always()
      run: |
        npx github-actions-ctrf test-results/report.json